server:
  port: 8081
spring:
  application:
    name: early-autumn-user
eureka:
  client:
    service-url:
      defaultZone: http://localhost/eureka
#      defaultZone: http://eurekaNodeOne.com/eureka,http://eurekaNodeTwo.com/eureka,http://eurekaNodeThree.com/eureka

  instance:
    instance-id: early-autumn-user

