server:
  port: 8081
spring:
  application:
    name: early-autumn-user
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka
#      defaultZone: http://eurekaNodeOne.com/eureka,http://eurekaNodeTwo.com/eureka,http://eurekaNodeThree.com/eureka

  instance:
    hostname: localhost
    instance-id: early-autumn-user
    prefer-ip-address: true



info:
  app.name: user
  company.name: ZGZ
#  build.artifactId: $proj
#  build.version: $project.version$

