#实例名称
spring:
  application:
    name: early-autumn-zuul
#端口号
server:
  port: 80

#服务注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://eurekaNodeOne.com/eureka,http://eurekaNodeTwo.com/eureka,http://eurekaNodeThree.com/eureka

zuul:
#统一访问前缀
  prefix: earlyautumn
#  routes:
#    routes后面接着的是服务名,path则为映射规则
#    early-autumn-user:
#      path: /user/**
#    account:
#      path: /account/**
#      serviceId: eureka-provider-account
#不给外部提供访问权限，只给内部client提供调用
  ignored-services: early-autumn-user
