spring:
  profiles:
    active: node-one

---
server:
  port: 9001


eureka:
  instance:
    hostname: localhost
#    hostname: eurekaNodeOne.com
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:9001/eureka
#      defaultZone: http://eurekaNodeTwo.com/eureka,http://eurekaNodeThree.com/eureka
spring:
  profiles: node-one
  application:
    name: eureka-node-one
---
server:
  port: 9002

eureka:
  instance:
    hostname: eurekaNodeTwo.com
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eurekaNodeOne.com/eureka,http://eurekaNodeThree.com/eureka
spring:
  profiles: node-two
  application:
    name: eureka-node-two

---
server:
  port: 9003

eureka:
  instance:
    hostname: eurekaNodeThree.com
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eurekaNodeOne.com/eureka,http://eurekaNodeTwo.com/eureka
spring:
  profiles: node-three
  application:
    name: eureka-node-three



